---
title: "Homework 3"
editor: source
format:
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
  warning: false # use this to make sure warnings don't show up
---

# Repository Link

[https://github.com/eckdogg/ENVS-193DS_homework-03.git]


# Set up

```{r}
library("tidyverse")
library("here")
library("gt")
library("janitor")
library("readxl")
library("ggplot2")
```


# Problem 1. Personal data

## a.

[To summarize my data I could compare the mean number of floors climbed (my response variable) on school days compared to non school days. I like to hike on the weekends so I think that I will climb more floors on non school days.]

## b.

```{r}
personaldata <- read_csv(here("data", "personaldata.csv")) 
personaldata_clean <- personaldata |> clean_names()

ggplot(data = personaldata_clean, # start with the personaldata_clean data frame
       aes(x = school_day, # x-axis should be type of day
           y = floors_climbed, # y-axis should be number of floors climbed 
           color = school_day)) + # coloring by type of day
  geom_boxplot() + # first layer should be a boxplot
  geom_jitter(width = 0.2, # making the points jitter horizontally
              height = 0) + # making sure points don't jitter vertically
  labs(x = "School Day", # labelling the x-axis
       y = "Floors Climbed") + # labelling the y-axis
   scale_color_manual(values = c("Yes" = "deepskyblue2", "No" = "deeppink2"))  + # removes the legend
  theme(legend.position = "none")
```



